## Numpy : 
#### NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of  routines for processing those arrays.


## Array : 
#### An array is a data structure that stores valuesof same data type.


In [2]:
## initially lets import numpy

import numpy as np  #(use aliases )

### One Dimensional Array :

In [4]:
#create a list 
my_lst=[1,2,3,4,5]   #define all the elements
arr=np.array(my_lst) #used np as aliases (.array) it creates an array based on the data type or element provided

In [5]:
#To see which type of array we are using 
type(arr)    #check the data type

numpy.ndarray

In [6]:
#to check which array we are using use inbulilt function
arr.shape    #helps you to specify how many no. of rows and columns are present  

(5,)

### Multinested Array :

In [20]:
# multidimensional array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]         #create more than 1 list for MD array

arr=np.array([my_lst1,my_lst2,my_lst3])    #in order to convert lst into array 

In [21]:
#in two-dimensional we'll have 2 opening brackets and 2 closing broackets
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [11]:
arr.shape  

(3, 5)

In [13]:
arr.reshape(5,3)    # returns an array containing the same data with a new shape.

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [14]:
arr.reshape(1,15)    #you can also use this type to reshape

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

### Indexing :

In [40]:
# Accessing the array elements
arr=np.array([1,2,3,4,5,6,7,8,9])

In [17]:
arr[3]     #the indexing starts from 0th position 

4

In [22]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [23]:
arr[:,:]                                   #left handside provides which row index you want.
                                         #(:)basically you pick up all the rows and colum indexes. 

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [26]:
arr[0:2,0:2]                              #  until the 2nd index in a row pick up all the rows

array([[1, 2],
       [2, 3]])

In [29]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [32]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [36]:
#inbuild function arange  
arr=np.arange(0,10, step=2)                     #return evenly spaced within a given interval 
                                                #step 2= going to take  agap of 2

In [37]:
arr

array([0, 2, 4, 6, 8])

In [41]:
#copy function and broadcasting
arr[3:]=50

In [42]:
arr

array([ 1,  2,  3, 50, 50, 50, 50, 50, 50])

In [44]:
arr1=arr

In [45]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [46]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [47]:
arr1=arr.copy()      #copy is creating an another memory space to store the value of arr1

In [48]:
print(arr)                    
arr1[3:]=1000                       #replaced arr1 by 3rd index 
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [49]:
# Some condiotons used in EDA
val=2          #defined a variable val
arr>2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [50]:
arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [51]:
arr/2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [53]:
arr%2

array([1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [55]:
arr[arr<300]

array([1, 2, 3])

In [62]:
np.ones(5,dtype=int)      #basically all the arrays are replaced by 1's five time

array([1, 1, 1, 1, 1])

In [61]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
#Random Distribution
np.random.rand(2,4)

array([[0.23090629, 0.15767117, 0.46890558, 0.83163846],
       [0.17534233, 0.5007153 , 0.04992302, 0.355473  ]])